name: Repository Maintenance

on:
  schedule:
    - cron: "30 1 * * *"
  pull_request:
    types: [labeled, opened, synchronize, reopened, ready_for_review]

permissions:
  issues: write
  pull-requests: write
  contents: write

jobs:
  stale:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue is stale because it has been open 30 days with no activity.'
          days-before-stale: 30
          days-before-close: 7

  automerge:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.user.login == 'dboone323' && contains(github.event.pull_request.labels.*.name, 'github-actions')
    steps:
      - name: Automerge PR
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GH_TOKEN}}
